#!/usr/bin/env ansible-playbook

---
- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install RabbitMQ
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "vm_memory_high_watermark"
      prompt: "Percentage of memory to allow RabbitMQ to use"
      private: no
      default: "0.9"
    - name: "ulimit"
      prompt: "The maximum number of file handles. 4096 for development, 65535 for production."
      private: no
      default: "4096"
  tasks:
    - debug: msg="vm_memory_high_watermark = {{ vm_memory_high_watermark }}"
    - debug: msg="ulimit = {{ ulimit }}"
    - name: Install Repository keys
      apt_key: state=present url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    - name: Install RabbitMQ repository
      apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
    - name: Install RabbitMQ
      apt: name=rabbitmq-server state=latest update_cache=true cache_valid_time=600
    - name: Copy the custom configuration file into /etc/rabbitmq 
      template: src=templates/rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config mode=0444 backup=yes force=yes
    - name: Copy the enabled plugins configuration file 
      copy: src=files/enabled_plugins dest=/etc/rabbitmq/enabled_plugins mode=0444 backup=no force=yes
    - name: Copy the custom configuration file into /etc/default 
      template: src=templates/rabbitmq-server dest=/etc/default/rabbitmq-server mode=0444 backup=yes force=yes
    - name: Restart RabbitMQ 
      service: name=rabbitmq-server state=restarted
